# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='fie_type',
            new_name='file_type',
        ),
    ]
